In [2]:
import torch

In [9]:
x = torch.arange(15, dtype=torch.float16)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14.], dtype=torch.float16)

In [12]:
x.numel()
x.shape

torch.Size([15])

In [16]:
x = x.reshape(3, 1, -1)
x

tensor([[[ 0.,  1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.,  9.]],

        [[10., 11., 12., 13., 14.]]], dtype=torch.float16)

In [18]:
x = torch.randn(3,6)
x

tensor([[-0.1624, -1.2329,  0.5889, -0.6708, -0.5115,  1.2340],
        [-0.3128, -0.1304,  0.8473,  0.7862,  1.6915,  0.1688],
        [-0.4110,  0.1870, -0.9228,  0.5538, -0.3205, -0.3975]])

In [25]:
x[1], x[1:3], x[1:-1]

(tensor([-0.3128, -0.1304,  0.8473,  0.7862,  1.6915,  0.1688]),
 tensor([[-0.3128, -0.1304,  0.8473,  0.7862,  1.6915,  0.1688],
         [-0.4110,  0.1870, -0.9228,  0.5538, -0.3205, -0.3975]]),
 tensor([[-0.3128, -0.1304,  0.8473,  0.7862,  1.6915,  0.1688]]))

In [28]:
x[1,2] = 17
x

tensor([[-0.1624, -1.2329,  0.5889, -0.6708, -0.5115,  1.2340],
        [-0.3128, -0.1304, 17.0000,  0.7862,  1.6915,  0.1688],
        [-0.4110,  0.1870, -0.9228,  0.5538, -0.3205, -0.3975]])

In [32]:
x[:2, :] = 12
x

tensor([[12.0000, 12.0000, 12.0000, 12.0000, 12.0000, 12.0000],
        [12.0000, 12.0000, 12.0000, 12.0000, 12.0000, 12.0000],
        [-0.4110,  0.1870, -0.9228,  0.5538, -0.3205, -0.3975]])

In [34]:
torch.exp(x)

tensor([[1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
        [1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
        [6.6300e-01, 1.2057e+00, 3.9742e-01, 1.7399e+00, 7.2579e-01, 6.7203e-01]])

In [36]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([2,2,2,2])

x + y, x - y, x * y, x / y

(tensor([3, 4, 5, 6]),
 tensor([-1,  0,  1,  2]),
 tensor([2, 4, 6, 8]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]))

In [41]:
x = torch.arange(15, dtype=torch.float16).reshape(3,5)
y = torch.tensor([[1,2,3,4,1], [4,3,2,1,1], [5,4,3,2,1]])
torch.cat((x,y), dim=0), torch.cat((x,y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [ 1.,  2.,  3.,  4.,  1.],
         [ 4.,  3.,  2.,  1.,  1.],
         [ 5.,  4.,  3.,  2.,  1.]], dtype=torch.float16),
 tensor([[ 0.,  1.,  2.,  3.,  4.,  1.,  2.,  3.,  4.,  1.],
         [ 5.,  6.,  7.,  8.,  9.,  4.,  3.,  2.,  1.,  1.],
         [10., 11., 12., 13., 14.,  5.,  4.,  3.,  2.,  1.]],
        dtype=torch.float16))

In [43]:
x == y

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [70]:
a = torch.arange(9).reshape((9,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]]),
 tensor([[0, 1]]))

In [61]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 6],
        [6, 7],
        [7, 8],
        [8, 9]])

In [62]:
before = id(b)
b = b + a
id(b) == before

False

In [64]:
Z = torch.zeros_like(b)
print('id(Z):', id(Z))
Z[:] = b+a
print('id(Z):', id(Z))

id(Z): 140037343397072
id(Z): 140037343397072


In [75]:
a = torch.arange(9).reshape((9,1))
b = torch.arange(2).reshape((1,2))
before = id(Z)
Z += a

before == id(Z)

True

In [76]:
A = a.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [77]:
a = torch.tensor([3.9])
a, a.item(), float(a), int(a)

(tensor([3.9000]), 3.9000000953674316, 3.9000000953674316, 3)