In [2]:
import torch

In [3]:
# scalars

x1 = torch.tensor(3.0)
x2 = torch.tensor(2.0)

x3 = x1 + x2

x1, x2, x3, x2 / x3

(tensor(3.), tensor(2.), tensor(5.), tensor(0.4000))

In [4]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [6]:
x[2]
len(x)
x.shape

torch.Size([3])

In [9]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [10]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [11]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [12]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [16]:
A = torch.arange(6, dtype=torch.float32).reshape(3, 2)
B = A.clone()
A, A + B, A * B, A * 2, A + 2, (A * 2).shape 

(tensor([[0., 1.],
         [2., 3.],
         [4., 5.]]),
 tensor([[ 0.,  2.],
         [ 4.,  6.],
         [ 8., 10.]]),
 tensor([[ 0.,  1.],
         [ 4.,  9.],
         [16., 25.]]),
 tensor([[ 0.,  2.],
         [ 4.,  6.],
         [ 8., 10.]]),
 tensor([[2., 3.],
         [4., 5.],
         [6., 7.]]),
 torch.Size([3, 2]))