In [1]:
import torch

In [2]:
# scalars

x1 = torch.tensor(3.0)
x2 = torch.tensor(2.0)

x3 = x1 + x2

x1, x2, x3, x2 / x3

(tensor(3.), tensor(2.), tensor(5.), tensor(0.4000))

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [4]:
x[2]
len(x)
x.shape

torch.Size([3])

In [5]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [6]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [7]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [8]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [9]:
A = torch.arange(6, dtype=torch.float32).reshape(3, 2)
B = A.clone()
A, A + B, A * B, A * 2, A + 2, (A * 2).shape 

(tensor([[0., 1.],
         [2., 3.],
         [4., 5.]]),
 tensor([[ 0.,  2.],
         [ 4.,  6.],
         [ 8., 10.]]),
 tensor([[ 0.,  1.],
         [ 4.,  9.],
         [16., 25.]]),
 tensor([[ 0.,  2.],
         [ 4.,  6.],
         [ 8., 10.]]),
 tensor([[2., 3.],
         [4., 5.],
         [6., 7.]]),
 torch.Size([3, 2]))

In [10]:
x = torch.arange(8, dtype=torch.float32).reshape(4, 2)
x, x.sum(), x.mean(), x.std(), x.shape, x.sum(axis=0), x.sum(axis=1), x.sum(axis=[0,1]), x.sum(axis=[0,1]) == x.sum()

(tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.]]),
 tensor(28.),
 tensor(3.5000),
 tensor(2.4495),
 torch.Size([4, 2]),
 tensor([12., 16.]),
 tensor([ 1.,  5.,  9., 13.]),
 tensor(28.),
 tensor(True))

In [11]:
x.mean(), x.sum() / x.numel(), x.numel(), x.sum()

(tensor(3.5000), tensor(3.5000), 8, tensor(28.))

In [12]:
x.mean(axis=0), x.sum(axis=0) / x.shape[0]

(tensor([3., 4.]), tensor([3., 4.]))

In [18]:
sum_A = x.sum(axis=1, keepdim=True)
sum_B = x.sum(axis=1)
sum_A, sum_A.shape, sum_B, x, x.sum(axis=1, keepdim=False)

(tensor([[ 1.],
         [ 5.],
         [ 9.],
         [13.]]),
 torch.Size([4, 1]),
 tensor([ 1.,  5.,  9., 13.]),
 tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.]]),
 tensor([ 1.,  5.,  9., 13.]))

In [19]:
x / sum_A

tensor([[0.0000, 1.0000],
        [0.4000, 0.6000],
        [0.4444, 0.5556],
        [0.4615, 0.5385]])

In [21]:
x.cumsum(axis=0)

tensor([[ 0.,  1.],
        [ 2.,  4.],
        [ 6.,  9.],
        [12., 16.]])

In [38]:
# dot or inner product
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y), x * y, torch.sum(x * y)

(tensor([0., 1., 2.]),
 tensor([1., 1., 1.]),
 tensor(3.),
 tensor([0., 1., 2.]),
 tensor(3.))

In [39]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
A, x, A.shape, x.shape, torch.mv(A, x), A@x, A * x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]),
 torch.Size([2, 3]),
 torch.Size([3]),
 tensor([ 5., 14.]),
 tensor([ 5., 14.]),
 tensor([[ 0.,  1.,  4.],
         [ 0.,  4., 10.]]))

In [43]:
B = torch.ones(3,4)
A, B, A.shape, B.shape, A @ B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([2, 3]),
 torch.Size([3, 4]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [ ]:
# norm or manhattan distance -> calculate the magnitude of a vector
u = torch.tensor([3.0, -4.0])
torch.norm(u), torch.norm(u, p=1), torch.norm(u, p=2), torch.norm(u, p=float('inf'))

(tensor(5.), tensor(7.), tensor(5.), tensor(4.))

In [48]:
# l1 norm
torch.abs(u).sum()

tensor(7.)

In [54]:
# frobenius norm -> normalize all the scalar values in a tensor
torch.norm(torch.ones(4, 9))

tensor(6.)

In [ ]:
#spectra norm
A = torch.tensor([[3.0, 0.0], [0.0, 2.0]])
torch.linalg.norm(A, ord=2)  # largest singular value

tensor(3.2566)